services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: mlflow server --host 0.0.0.0 --backend-store-uri /mlflow/mlruns --default-artifact-root /mlflow/mlruns
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
